name: 'Fetch and Filter IPs'

on:
  schedule:
    - cron: '21 */4 * * *' # 每 4 小时第 21 分钟自动运行一次
  workflow_dispatch:      # 支持手动触发运行

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'Install dependencies'
        run: pip install requests

      - name: 'Run Filter Script'
        env:
          NAS_USER: ${{ secrets.NAS_USER }}
          NAS_PASS: ${{ secrets.NAS_PASS }}
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
          WEBDAV_URL2: ${{ secrets.WEBDAV_URL2 }}
        run: python dnscf.py

      - name: 'Commit and Push Changes'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ips.txt jp.txt sg.txt jp8443.txt sg8443.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "自动更新优选国别 IP 列表 (JP/SG/443/8443)" && git push)
